### ISSUE TITLE
用videoproc 检测，H264可用，HEVC不可用。是

### ISSUE THREAD

**Issue by zorroye** [Augustl-18/Lenovo-Y9000X-2020-9750H-4K-Hackintosh#4]
我哪里配置问题吗，，，我的也是y9000x 2020款。9750H。 但是是1080p的，我把dpcd-max-link-rate 改成0A000000了。是这个问题吗？

**Comment by zorroye** [comment]
按国光的方法，删除。DeviceProperties 设备属性设置里面的核显设备，删除 AAPL,slot-name 即可。

**Comment by Augustl-18** [comment]
我的正常的，可能是机型不一样
















在 2022-11-01 22:26:06，"zorroye" ***@***.***> 写道：

我哪里配置问题吗，，，我的也是y9000x 2020款。9750H。 但是是1080p的，我把dpcd-max-link-rate 改成0A000000了。是这个问题吗？
